### ISSUE TITLE
Interface com BOT do Telegram

### ISSUE THREAD

**Issue by brenocoe** [schreibfaul1/ESP32-Astronomie#3]
E por último, gostaria de sugerir que me permita portar uma interface com o Telegram para essa biblioteca,

Imagino que nesse BOT poderíamos receber a latitude e longitude e pegar a hora atual e instanciar o objeto "Astronomy" com os dados do usuário que estiver conversando com o BOT.

Atenciosamente, 

Breno Coe.

**Comment by schreibfaul1** [comment]
Leider habe ich keine Ahnung wie der Telegram Bot funktioniert. Wie kann man die geographische Länge und Breite einlesen?
